backend:
  name: git-gateway
  branch: main # Branch to update

publish_mode: editorial_workflow
media_folder: "public/uploads" # Media will be stored in the repo under public/uploads
public_folder: "/uploads" # The src attribute for uploaded media
local_backend: true # Enables local development

site_url: https://lawsofexistence.com
display_url: https://lawsofexistence.com
logo_url: https://lawsofexistence.com/favicon.ico

collections:
  - name: manuscript
    label: Manuscript & White Papers
    folder: content/manuscript
    create: true
    format: json
    identifier_field: title
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Collection Type, name: collection_type, widget: hidden, default: manuscript}
      - label: Sections
        name: sections
        widget: list
        allow_add: true
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Featured, name: featured, widget: boolean, default: false}
          - {label: Basic Content (Level 1), name: content_level_1, widget: markdown, required: false}
          - {label: Intermediate Content (Level 3), name: content_level_3, widget: markdown}
          - {label: Advanced Content (Level 5), name: content_level_5, widget: markdown, required: false}
  - name: data
    label: Data & Evidence
    folder: content/data
    create: true
    format: json
    identifier_field: title
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Collection Type, name: collection_type, widget: hidden, default: data}
      - label: Sections
        name: sections
        widget: list
        allow_add: true
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Featured, name: featured, widget: boolean, default: false}
          - {label: Basic Content (Level 1), name: content_level_1, widget: markdown, required: false}
          - {label: Intermediate Content (Level 3), name: content_level_3, widget: markdown}
          - {label: Advanced Content (Level 5), name: content_level_5, widget: markdown, required: false}